# Generated by Django 5.1.5 on 2025-01-21 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='developer_type',
            field=models.CharField(choices=[('front-end', 'FrontEnd'), ('back-end', 'BackEnd'), ('qa', 'QA'), ('none', 'None')], default='None', max_length=20),
        ),
    ]
