# Generated by Django 5.1.5 on 2025-01-23 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='deadline',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='assigned_on',
            field=models.DateField(auto_now_add=True),
        ),
    ]
