# Generated by Django 5.1.5 on 2025-01-23 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_task_time_to_complete_alter_project_assigned_on_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='flag',
            field=models.CharField(choices=[('red', 'Red'), ('yellow', 'Yellow'), ('green', 'Green')], default='yellow', max_length=20),
        ),
    ]
