# Generated by Django 5.1.5 on 2025-01-23 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_task_flag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='flag',
            field=models.CharField(choices=[('red', 'Red'), ('yellow', 'Yellow'), ('green', 'Green'), ('none', 'None')], default='none', max_length=20),
        ),
    ]
