# Generated by Django 5.1.5 on 2025-01-24 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_alter_task_flag'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='projects_assigned',
            field=models.ManyToManyField(null=True, related_name='project', to='user.project'),
        ),
    ]
