# Generated by Django 5.1.5 on 2025-01-24 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_user_projects_assigned'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='projects_assigned',
            field=models.ManyToManyField(blank=True, related_name='project', to='user.project'),
        ),
    ]
