# Generated by Django 5.1.5 on 2025-01-24 05:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_alter_user_projects_assigned'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='projects_assigned',
        ),
    ]
