# Generated by Django 5.1.5 on 2025-01-30 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0010_client_project_paid_project_status_project_client'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='time_taken',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
